Repository ScrapeGraphAI/Scrapegraph-ai, pull requests merged in 2025-04, with the labels that each got.

#962 tune scraper
  scrapegraphai/docloaders/chromium.py
  scrapegraphai/utils/cleanup_html.py
  scrapegraphai/utils/proxy_rotation.py
Labels: refactor, size:L

#971 allignment
  CHANGELOG.md
  pyproject.toml
Labels: size:S

#972 feat: enhance error handling and validation across utility modules
  scrapegraphai/utils/code_error_analysis.py
  scrapegraphai/utils/code_error_correction.py
  scrapegraphai/utils/research_web.py
Labels: enhancement, size:XXL

#973 Pre/beta
  CHANGELOG.md
  pyproject.toml
  scrapegraphai/helpers/models_tokens.py
Labels: size:XS
