Repository ScrapeGraphAI/Scrapegraph-ai, pull requests merged in 2025-03, with the labels that each got.

#940 feat: add CLoD integration
  scrapegraphai/graphs/abstract_graph.py
  scrapegraphai/helpers/models_tokens.py
  scrapegraphai/models/__init__.py
  scrapegraphai/models/clod.py
  tests/graphs/.env.example
  tests/graphs/smart_scraper_clod_test.py
  uv.lock
Labels: enhancement, tests, size:L

#943 Pre/beta
  CHANGELOG.md
  pyproject.toml
  scrapegraphai/graphs/abstract_graph.py
  scrapegraphai/helpers/models_tokens.py
  scrapegraphai/models/__init__.py
  scrapegraphai/models/clod.py
  tests/graphs/.env.example
  tests/graphs/abstract_graph_test.py
  tests/graphs/smart_scraper_clod_test.py
  tests/test_models_tokens.py
  uv.lock
Labels: size:L

#951 Update llm.rst
  docs/source/scrapers/llm.rst
Labels: documentation, size:XS, lgtm

#946 Fix schema option not working
  CHANGELOG.md
  README.md
  docs/chinese.md
  docs/japanese.md
  docs/korean.md
  docs/russian.md
  docs/source/conf.py
  docs/turkish.md
  examples/ScrapegraphAI_cookbook.ipynb
  examples/document_scraper_graph/ollama/inputs/plain_html_example.txt
  examples/document_scraper_graph/openai/inputs/markdown_example.md
  examples/document_scraper_graph/openai/inputs/plain_html_example.txt
  examples/extras/cond_smartscraper_usage.py
  examples/smart_scraper_graph/ollama/smart_scraper_lite_ollama.py
  examples/smart_scraper_graph/ollama/smart_scraper_multi_concat_ollama.py
  examples/smart_scraper_graph/ollama/smart_scraper_multi_lite_ollama.py
  examples/smart_scraper_graph/ollama/smart_scraper_multi_ollama.py
  examples/smart_scraper_graph/openai/smart_scraper_lite_openai.py
  examples/smart_scraper_graph/openai/smart_scraper_multi_concat_openai.py
  examples/smart_scraper_graph/openai/smart_scraper_multi_lite_openai.py
  examples/smart_scraper_graph/openai/smart_scraper_multi_openai.py
  pyproject.toml
  scrapegraphai/graphs/abstract_graph.py
  scrapegraphai/graphs/smart_scraper_multi_graph.py
  scrapegraphai/graphs/smart_scraper_multi_lite_graph.py
  scrapegraphai/helpers/models_tokens.py
  scrapegraphai/nodes/generate_answer_node.py
  tests/graphs/inputs/plain_html_example.txt
  tests/graphs/smart_scraper_multi_lite_graph_openai_test.py
  tests/graphs/smart_scraper_openai_test.py
  tests/inputs/plain_html_example.txt
  tests/nodes/inputs/plain_html_example.txt
  uv.lock
Labels: bug, tests, size:L, lgtm

#957 Pre/beta
  CHANGELOG.md
  pyproject.toml
  scrapegraphai/nodes/generate_answer_node.py
  tests/graphs/smart_scraper_openai_test.py
  uv.lock
Labels: dependencies, released on @dev, size:M
