Repository ScrapeGraphAI/Scrapegraph-ai, pull requests merged in 2025-06, with the labels that each got.

#982 Pre/beta
  CHANGELOG.md
  pyproject.toml
  scrapegraphai/graphs/abstract_graph.py
  scrapegraphai/helpers/models_tokens.py
  scrapegraphai/models/__init__.py
  scrapegraphai/models/xai.py
Labels: dependencies, released on @dev, size:M

#987 docs: add links to other language versions of README
  README.md
Labels: documentation, size:XS, lgtm

#992 fix: removed an extra space in TEMPLATE_CHUKS_CSV in generate_answer_node_…
  scrapegraphai/prompts/generate_answer_node_csv_prompts.py
Labels: typo, size:XS
