Repository ScrapeGraphAI/Scrapegraph-ai, pull requests merged in 2025-01, with the labels that each got.

#862 Pre/beta
  .github/workflows/release.yml
  CHANGELOG.md
  examples/extras/chromium_selenium.py
  pyproject.toml
  requirements-dev.txt
  scrapegraphai/docloaders/chromium.py
  scrapegraphai/graphs/abstract_graph.py
  scrapegraphai/helpers/models_tokens.py
  tests/graphs/abstract_graph_test.py
  uv.lock
Labels: released on @dev

#877 856 token indices sequence length
  examples/local_models/smart_scraper_ollama.py
  examples/local_models/smart_scraper_schema_ollama.py
  pyproject.toml
  scrapegraphai/docloaders/chromium.py
  scrapegraphai/graphs/abstract_graph.py
  scrapegraphai/nodes/generate_answer_node.py
  scrapegraphai/nodes/generate_answer_node_k_level.py
  scrapegraphai/nodes/parse_node.py
  scrapegraphai/utils/split_text_into_chunks.py
  scrapegraphai/utils/tokenizer.py
  scrapegraphai/utils/tokenizers/tokenizer_openai.py
  uv.lock
Labels: bug, enhancement, size:L

#883 Alignment
  CHANGELOG.md
  README.md
  pyproject.toml
Labels: documentation, dependencies, size:M

#895 fix: Schema parameter type
  scrapegraphai/graphs/abstract_graph.py
  scrapegraphai/graphs/code_generator_graph.py
  scrapegraphai/graphs/csv_scraper_graph.py
  scrapegraphai/graphs/csv_scraper_multi_graph.py
  scrapegraphai/graphs/depth_search_graph.py
  scrapegraphai/graphs/document_scraper_graph.py
  scrapegraphai/graphs/document_scraper_multi_graph.py
  scrapegraphai/graphs/json_scraper_graph.py
  scrapegraphai/graphs/json_scraper_multi_graph.py
  scrapegraphai/graphs/omni_scraper_graph.py
  scrapegraphai/graphs/omni_search_graph.py
  scrapegraphai/graphs/screenshot_scraper_graph.py
  scrapegraphai/graphs/script_creator_graph.py
  scrapegraphai/graphs/script_creator_multi_graph.py
  scrapegraphai/graphs/search_graph.py
  scrapegraphai/graphs/search_link_graph.py
  scrapegraphai/graphs/smart_scraper_graph.py
  scrapegraphai/graphs/smart_scraper_lite_graph.py
  scrapegraphai/graphs/smart_scraper_multi_concat_graph.py
  scrapegraphai/graphs/smart_scraper_multi_graph.py
  scrapegraphai/graphs/smart_scraper_multi_lite_graph.py
  scrapegraphai/graphs/speech_graph.py
  scrapegraphai/graphs/xml_scraper_graph.py
  scrapegraphai/graphs/xml_scraper_multi_graph.py
  scrapegraphai/nodes/graph_iterator_node.py
Labels: size:L, lgtm

#904 Pre/beta
  CHANGELOG.md
  codebeaver.yml
  pyproject.toml
  scrapegraphai/graphs/abstract_graph.py
  scrapegraphai/graphs/code_generator_graph.py
  scrapegraphai/graphs/csv_scraper_graph.py
  scrapegraphai/graphs/csv_scraper_multi_graph.py
  scrapegraphai/graphs/depth_search_graph.py
  scrapegraphai/graphs/document_scraper_graph.py
  scrapegraphai/graphs/document_scraper_multi_graph.py
  scrapegraphai/graphs/json_scraper_graph.py
  scrapegraphai/graphs/json_scraper_multi_graph.py
  scrapegraphai/graphs/omni_scraper_graph.py
  scrapegraphai/graphs/omni_search_graph.py
  scrapegraphai/graphs/screenshot_scraper_graph.py
  scrapegraphai/graphs/script_creator_graph.py
  scrapegraphai/graphs/script_creator_multi_graph.py
  scrapegraphai/graphs/search_graph.py
  scrapegraphai/graphs/search_link_graph.py
  scrapegraphai/graphs/smart_scraper_graph.py
  scrapegraphai/graphs/smart_scraper_lite_graph.py
  scrapegraphai/graphs/smart_scraper_multi_concat_graph.py
  scrapegraphai/graphs/smart_scraper_multi_graph.py
  scrapegraphai/graphs/smart_scraper_multi_lite_graph.py
  scrapegraphai/graphs/speech_graph.py
  scrapegraphai/graphs/xml_scraper_graph.py
  scrapegraphai/graphs/xml_scraper_multi_graph.py
  scrapegraphai/nodes/graph_iterator_node.py
  tests/graphs/abstract_graph_test.py
  tests/test_json_scraper_graph.py
  tests/test_search_graph.py
Labels: released on @dev, size:L
