Repository ScrapeGraphAI/Scrapegraph-ai, pull requests merged in 2025-05, with the labels that each got.

#977 fix: 🐛 Spelling fix for README.md
  README.md
Labels: typo, size:XS, lgtm

#978 ci(release): 1.50.0-beta.1 [skip ci]
  CHANGELOG.md
  pyproject.toml
Labels: size:S

#976 Fix for Issue #975. Reennabling Burr compatibilty for SmartScraperGraph
  scrapegraphai/nodes/fetch_node.py
  scrapegraphai/nodes/parse_node.py
Labels: bug, size:XS
