Repository ScrapeGraphAI/Scrapegraph-ai, pull requests merged in 2025-02, with the labels that each got.

#913 Allow to customize scrape.do proxy/api endpoints
  scrapegraphai/docloaders/scrape_do.py
Labels: enhancement, size:XS, lgtm

#920 Pre/beta
  tests/test_depth_search_graph.py
  tests/test_json_scraper_graph.py
  tests/test_search_graph.py
Labels: tests, size:L

#923 Pre/beta
  CHANGELOG.md
  pyproject.toml
  scrapegraphai/graphs/search_link_graph.py
Labels: size:S

#925 Pre/beta
  CHANGELOG.md
  docs/assets/api-banner.png
  pyproject.toml
  scrapegraphai/helpers/models_tokens.py
  scrapegraphai/nodes/generate_answer_node.py
Labels: dependencies, size:M

#932 Pre/beta
  CHANGELOG.md
  pyproject.toml
  scrapegraphai/nodes/generate_answer_node.py
  scrapegraphai/nodes/parse_node.py
  uv.lock
Labels: dependencies, released on @dev, size:M

#935 bugfix: KeyError mishap
  scrapegraphai/nodes/generate_answer_node.py
Labels: bug, size:XS

#936 Pre/beta
  tests/test_generate_answer_node.py
Labels: size:L
